Instructions page
kiphenglim/FA20-CS121 pull request #17
Opened 2020-11-07 19:29 UTC by skygering

2020-11-07 19:40 UTC, kiphenglim requested changes
Here are a couple of changes I would like you to make:

- remove the .DS_Store files and add them to the .gitignore. 
- move the screenshots out of the uploads folder and create a new folder for website images. I'm pretty sure that the uploads folder is for user uploads rather than our content, but @Sfreisem-Kirov or @vivpou will know if this is indeed the convention or not.
- introduce more empty lines and comments to separate the divs. It's currently pretty difficult to figure out where each panel begins and ends.

2020-11-08 22:46 UTC, Sfreisem-Kirov requested changes
you don't need the form, just add 
onclick="history.back()"
to the button

2020-11-08 22:47 UTC, Sfreisem-Kirov commented on templates/instructions.html
> -    <button type="submit">Back to Main Page</button>
you dont need the form here, just add onclick="history.back()" to the button

2020-11-10 04:33 UTC, kiphenglim approved these changes

2020-11-10 04:35 UTC, TLinhTCDLAL approved these changes

2020-11-10 04:39 UTC, kiphenglim approved these changes

2020-11-10 04:41 UTC, merged